apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
        - name: backend-server
          image: shalwineth/backend-server:latest
          ports:
            - containerPort: 8080
